data_ingestion:
  bucket_name: marco93_1
  bucket_file_name: "hotel_reservations.csv"
  train_ratio: 0.8

data_processing:
  target_column: "booking_status"
  dropped_columns:
    - "Booking_ID"
    - "arrival_year"
  categorical_columns:
    - "market_segment_type"
    - "type_of_meal_plan"
    - "room_type_reserved"
    - "required_car_parking_space"
    - "repeated_guest"
    - "booking_status"
  numerical_columns:
    - 'lead_time'
    - 'no_of_special_requests'
    - 'avg_price_per_room'
    - 'arrival_month'
    - 'arrival_date'
    - 'no_of_week_nights'
    - 'no_of_weekend_nights'
    - 'no_of_adults'
    - 'no_of_children'
    - 'no_of_previous_cancellations'
    - 'no_of_previous_bookings_not_canceled'
  skew_threshold: 5
